//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipBlock3D_LevelEditor.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlipBlock3D_LevelEditor.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Program.
        /// </summary>
        public static string sAboutProgram {
            get {
                return ResourceManager.GetString("sAboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells Count.
        /// </summary>
        public static string sCellsCount {
            get {
                return ResourceManager.GetString("sCellsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant Number of Steps.
        /// </summary>
        public static string sConstanNumberOfSteps {
            get {
                return ResourceManager.GetString("sConstanNumberOfSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Cell.
        /// </summary>
        public static string sCurrentCell {
            get {
                return ResourceManager.GetString("sCurrentCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleta all cells.
        /// </summary>
        public static string sDeletaAllCells {
            get {
                return ResourceManager.GetString("sDeletaAllCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this cell.
        /// </summary>
        public static string sDeleteThisCell {
            get {
                return ResourceManager.GetString("sDeleteThisCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct On Axis.
        /// </summary>
        public static string sDirectOnAxis {
            get {
                return ResourceManager.GetString("sDirectOnAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string sEdit {
            get {
                return ResourceManager.GetString("sEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration File of program not exist or it is corrupted.
        ///Program will open with default settings.
        ///If you open first time this program, pleas ignore this problem.
        ///If this problem occur every time during opening a program, please start program with Administrator Rights..
        /// </summary>
        public static string sErrorConfigFileNoExistMessage {
            get {
                return ResourceManager.GetString("sErrorConfigFileNoExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with Configuration File.
        /// </summary>
        public static string sErrorConfigFileNoExistTitle {
            get {
                return ResourceManager.GetString("sErrorConfigFileNoExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a correct level name..
        /// </summary>
        public static string sErrorIncorrectNameMessage {
            get {
                return ResourceManager.GetString("sErrorIncorrectNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect level name.
        /// </summary>
        public static string sErrorIncorrectNameTittle {
            get {
                return ResourceManager.GetString("sErrorIncorrectNameTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a correct level path..
        /// </summary>
        public static string sErrorIncorrectPathMessage {
            get {
                return ResourceManager.GetString("sErrorIncorrectPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect level path.
        /// </summary>
        public static string sErrorIncorrectPathTittle {
            get {
                return ResourceManager.GetString("sErrorIncorrectPathTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual cannot be open properly. Please check you PC can open PDF files.
        ///
        ///If PC can open PDF files pleas make following steps:
        ///1. Check program folder, if contains folder &quot;Manuals&quot;.
        ///2.  Check &quot;Manuals&quot; folder contains PDF file &quot;Flip Block 3D - Level Editor (User Manual).pdf&quot;.
        ///
        ///If any step is not met, please contact with person who distrbute this program..
        /// </summary>
        public static string sErrorManualOpenMessage {
            get {
                return ResourceManager.GetString("sErrorManualOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during open manual.
        /// </summary>
        public static string sErrorManualOpenTittle {
            get {
                return ResourceManager.GetString("sErrorManualOpenTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game level cannot be opened!
        ///File is corrupted..
        /// </summary>
        public static string sErrorOpenLevelMessage {
            get {
                return ResourceManager.GetString("sErrorOpenLevelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open level error.
        /// </summary>
        public static string sErrorOpenLevelTittle {
            get {
                return ResourceManager.GetString("sErrorOpenLevelTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The level path does not exist..
        /// </summary>
        public static string sErrorPathNoExistMessage {
            get {
                return ResourceManager.GetString("sErrorPathNoExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exist level path.
        /// </summary>
        public static string sErrorPathNoExistTittle {
            get {
                return ResourceManager.GetString("sErrorPathNoExistTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game level was not saved correct!
        ///Some unxpected error occure..
        /// </summary>
        public static string sErrorSaveLevelMessage {
            get {
                return ResourceManager.GetString("sErrorSaveLevelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during save level.
        /// </summary>
        public static string sErrorSaveLevelTittle {
            get {
                return ResourceManager.GetString("sErrorSaveLevelTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string sExit {
            get {
                return ResourceManager.GetString("sExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string sFile {
            get {
                return ResourceManager.GetString("sFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string sFinish {
            get {
                return ResourceManager.GetString("sFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Block 3D - Level Editor.
        /// </summary>
        public static string sFlipBlock3D_LevelEditor {
            get {
                return ResourceManager.GetString("sFlipBlock3D_LevelEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Level.
        /// </summary>
        public static string sGameLevel {
            get {
                return ResourceManager.GetString("sGameLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string sHelp {
            get {
                return ResourceManager.GetString("sHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Cell 
        ///Number of Steps = 1.
        /// </summary>
        public static string sIceCell1 {
            get {
                return ResourceManager.GetString("sIceCell1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Cell
        ///Number of Steps = 2.
        /// </summary>
        public static string sIceCell2 {
            get {
                return ResourceManager.GetString("sIceCell2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Cell
        ///Number of Steps = 3.
        /// </summary>
        public static string sIceCell3 {
            get {
                return ResourceManager.GetString("sIceCell3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Cell 
        ///Number of Steps = 4.
        /// </summary>
        public static string sIceCell4 {
            get {
                return ResourceManager.GetString("sIceCell4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice cells.
        /// </summary>
        public static string sIceCells {
            get {
                return ResourceManager.GetString("sIceCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrement Number of Steps in Ice Cell.
        /// </summary>
        public static string sIceDec1 {
            get {
                return ResourceManager.GetString("sIceDec1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Number of Steps in Ice Cell.
        /// </summary>
        public static string sIceInc1 {
            get {
                return ResourceManager.GetString("sIceInc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game level was created!.
        /// </summary>
        public static string sInfoNewLevelConfirmationMessage {
            get {
                return ResourceManager.GetString("sInfoNewLevelConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New level confirmation.
        /// </summary>
        public static string sInfoNewLevelConfirmationTittle {
            get {
                return ResourceManager.GetString("sInfoNewLevelConfirmationTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game level was opened correct!.
        /// </summary>
        public static string sInfoOpenLevelConfirmationMessage {
            get {
                return ResourceManager.GetString("sInfoOpenLevelConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open level confirmation.
        /// </summary>
        public static string sInfoOpenLevelConfirmationTittle {
            get {
                return ResourceManager.GetString("sInfoOpenLevelConfirmationTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game level was saved correct!.
        /// </summary>
        public static string sInfoSaveLevelMessage {
            get {
                return ResourceManager.GetString("sInfoSaveLevelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save level confiramtion.
        /// </summary>
        public static string sInfoSaveLevelTittle {
            get {
                return ResourceManager.GetString("sInfoSaveLevelTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string sLanguage {
            get {
                return ResourceManager.GetString("sLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level dimension control.
        /// </summary>
        public static string sLevelDimensionControl {
            get {
                return ResourceManager.GetString("sLevelDimensionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level dimension information.
        /// </summary>
        public static string sLevelDimensionInformation {
            get {
                return ResourceManager.GetString("sLevelDimensionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All Level To
        ///Bottom Left Corner.
        /// </summary>
        public static string sMoveViewBottomLeft {
            get {
                return ResourceManager.GetString("sMoveViewBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All Level To
        ///Bottom Right Corner.
        /// </summary>
        public static string sMoveViewBottomRight {
            get {
                return ResourceManager.GetString("sMoveViewBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All Level To
        ///Down Direction.
        /// </summary>
        public static string sMoveViewDown {
            get {
                return ResourceManager.GetString("sMoveViewDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All Level To
        ///Left Direction.
        /// </summary>
        public static string sMoveViewLeft {
            get {
                return ResourceManager.GetString("sMoveViewLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All Level To
        ///Right Direction.
        /// </summary>
        public static string sMoveViewRight {
            get {
                return ResourceManager.GetString("sMoveViewRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All Level To
        ///Top Left Corner.
        /// </summary>
        public static string sMoveViewTopLeft {
            get {
                return ResourceManager.GetString("sMoveViewTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All Level To
        ///Top Right Corner.
        /// </summary>
        public static string sMoveViewTopRight {
            get {
                return ResourceManager.GetString("sMoveViewTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All Level To
        ///Up Direction.
        /// </summary>
        public static string sMoveViewUp {
            get {
                return ResourceManager.GetString("sMoveViewUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Level.
        /// </summary>
        public static string sNewLevel {
            get {
                return ResourceManager.GetString("sNewLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Cell 
        ///Number of Steps = 1.
        /// </summary>
        public static string sNormalCell1 {
            get {
                return ResourceManager.GetString("sNormalCell1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Cell
        ///Number of Steps = 2.
        /// </summary>
        public static string sNormalCell2 {
            get {
                return ResourceManager.GetString("sNormalCell2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Cell
        ///Number of Steps = 3.
        /// </summary>
        public static string sNormalCell3 {
            get {
                return ResourceManager.GetString("sNormalCell3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Cell 
        ///Number of Steps = 4.
        /// </summary>
        public static string sNormalCell4 {
            get {
                return ResourceManager.GetString("sNormalCell4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Cells.
        /// </summary>
        public static string sNormalCells {
            get {
                return ResourceManager.GetString("sNormalCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrement Number of Steps in Normal Cell.
        /// </summary>
        public static string sNormalDec {
            get {
                return ResourceManager.GetString("sNormalDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Number of Steps in Normal Cell.
        /// </summary>
        public static string sNormalInc {
            get {
                return ResourceManager.GetString("sNormalInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of steps.
        /// </summary>
        public static string sNumberOfSteps {
            get {
                return ResourceManager.GetString("sNumberOfSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of StepsModyfier.
        /// </summary>
        public static string sNumberOfStepsModyfier {
            get {
                return ResourceManager.GetString("sNumberOfStepsModyfier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Level.
        /// </summary>
        public static string sOpenLevel {
            get {
                return ResourceManager.GetString("sOpenLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Manual.
        /// </summary>
        public static string sOpenManual {
            get {
                return ResourceManager.GetString("sOpenManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Cells.
        /// </summary>
        public static string sOtherCells {
            get {
                return ResourceManager.GetString("sOtherCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position X.
        /// </summary>
        public static string sPositionX {
            get {
                return ResourceManager.GetString("sPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Y.
        /// </summary>
        public static string sPositionY {
            get {
                return ResourceManager.GetString("sPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Path.
        /// </summary>
        public static string sProjectPath {
            get {
                return ResourceManager.GetString("sProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string sReleaseDate {
            get {
                return ResourceManager.GetString("sReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize view to all cells.
        /// </summary>
        public static string sResizeViewToAllCells {
            get {
                return ResourceManager.GetString("sResizeViewToAllCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Level.
        /// </summary>
        public static string sSaveLevel {
            get {
                return ResourceManager.GetString("sSaveLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Level as....
        /// </summary>
        public static string sSaveLevelAs3xDot {
            get {
                return ResourceManager.GetString("sSaveLevelAs3xDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Defoult View.
        /// </summary>
        public static string sSetDefoultView {
            get {
                return ResourceManager.GetString("sSetDefoultView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Bottom Status Bar.
        /// </summary>
        public static string sShowBottomStatusBar {
            get {
                return ResourceManager.GetString("sShowBottomStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Left Panel.
        /// </summary>
        public static string sShowLeftPanel {
            get {
                return ResourceManager.GetString("sShowLeftPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Right Panel.
        /// </summary>
        public static string sShowRightPanel {
            get {
                return ResourceManager.GetString("sShowRightPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tool Bar.
        /// </summary>
        public static string sShowToolBar {
            get {
                return ResourceManager.GetString("sShowToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string sStart {
            get {
                return ResourceManager.GetString("sStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Bar Icons Size.
        /// </summary>
        public static string sToolBarIconsSize {
            get {
                return ResourceManager.GetString("sToolBarIconsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string sType {
            get {
                return ResourceManager.GetString("sType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Number.
        /// </summary>
        public static string sVersionNumber {
            get {
                return ResourceManager.GetString("sVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string sView {
            get {
                return ResourceManager.GetString("sView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Navigation.
        /// </summary>
        public static string sViewNavigation {
            get {
                return ResourceManager.GetString("sViewNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In Level View.
        /// </summary>
        public static string sZoomInLevelView {
            get {
                return ResourceManager.GetString("sZoomInLevelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out Level View.
        /// </summary>
        public static string sZoomOutLevelView {
            get {
                return ResourceManager.GetString("sZoomOutLevelView", resourceCulture);
            }
        }
    }
}
