//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipBlock3D_LevelEditor.Languages {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlipBlock3D_LevelEditor.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu About Program.
        /// </summary>
        public static string sAboutProgram {
            get {
                return ResourceManager.GetString("sAboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cells Count.
        /// </summary>
        public static string sCellsCount {
            get {
                return ResourceManager.GetString("sCellsCount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Constant Number of Steps.
        /// </summary>
        public static string sConstanNumberOfSteps {
            get {
                return ResourceManager.GetString("sConstanNumberOfSteps", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Current Cell.
        /// </summary>
        public static string sCurrentCell {
            get {
                return ResourceManager.GetString("sCurrentCell", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Deleta all cells.
        /// </summary>
        public static string sDeletaAllCells {
            get {
                return ResourceManager.GetString("sDeletaAllCells", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete this cell.
        /// </summary>
        public static string sDeleteThisCell {
            get {
                return ResourceManager.GetString("sDeleteThisCell", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Direct On Axis.
        /// </summary>
        public static string sDirectOnAxis {
            get {
                return ResourceManager.GetString("sDirectOnAxis", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        public static string sEdit {
            get {
                return ResourceManager.GetString("sEdit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Configuration File of program not exist or it is corrupted.
        ///Program will open with default settings.
        ///If you open first time this program, pleas ignore this problem.
        ///If this problem occur every time during opening a program, please start program with Administrator Rights..
        /// </summary>
        public static string sErrorConfigFileNoExistMessage {
            get {
                return ResourceManager.GetString("sErrorConfigFileNoExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Problem with Configuration File.
        /// </summary>
        public static string sErrorConfigFileNoExistTitle {
            get {
                return ResourceManager.GetString("sErrorConfigFileNoExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a correct level name..
        /// </summary>
        public static string sErrorIncorrectNameMessage {
            get {
                return ResourceManager.GetString("sErrorIncorrectNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Incorrect level name.
        /// </summary>
        public static string sErrorIncorrectNameTittle {
            get {
                return ResourceManager.GetString("sErrorIncorrectNameTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Please select a correct level path..
        /// </summary>
        public static string sErrorIncorrectPathMessage {
            get {
                return ResourceManager.GetString("sErrorIncorrectPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Incorrect level path.
        /// </summary>
        public static string sErrorIncorrectPathTittle {
            get {
                return ResourceManager.GetString("sErrorIncorrectPathTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Manual cannot be open properly. Please check you PC can open PDF files.
        ///
        ///If PC can open PDF files pleas make following steps:
        ///1. Check program folder, if contains folder &quot;Manuals&quot;.
        ///2.  Check &quot;Manuals&quot; folder contains PDF file &quot;Flip Block 3D - Level Editor (User Manual).pdf&quot;.
        ///
        ///If any step is not met, please contact with person who distrbute this program..
        /// </summary>
        public static string sErrorManualOpenMessage {
            get {
                return ResourceManager.GetString("sErrorManualOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error during open manual.
        /// </summary>
        public static string sErrorManualOpenTittle {
            get {
                return ResourceManager.GetString("sErrorManualOpenTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game level cannot be opened!
        ///File is corrupted..
        /// </summary>
        public static string sErrorOpenLevelMessage {
            get {
                return ResourceManager.GetString("sErrorOpenLevelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open level error.
        /// </summary>
        public static string sErrorOpenLevelTittle {
            get {
                return ResourceManager.GetString("sErrorOpenLevelTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The level path does not exist..
        /// </summary>
        public static string sErrorPathNoExistMessage {
            get {
                return ResourceManager.GetString("sErrorPathNoExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No exist level path.
        /// </summary>
        public static string sErrorPathNoExistTittle {
            get {
                return ResourceManager.GetString("sErrorPathNoExistTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game level was not saved correct!
        ///Some unxpected error occure..
        /// </summary>
        public static string sErrorSaveLevelMessage {
            get {
                return ResourceManager.GetString("sErrorSaveLevelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error during save level.
        /// </summary>
        public static string sErrorSaveLevelTittle {
            get {
                return ResourceManager.GetString("sErrorSaveLevelTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Exit.
        /// </summary>
        public static string sExit {
            get {
                return ResourceManager.GetString("sExit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File.
        /// </summary>
        public static string sFile {
            get {
                return ResourceManager.GetString("sFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Finish.
        /// </summary>
        public static string sFinish {
            get {
                return ResourceManager.GetString("sFinish", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Flip Block 3D - Level Editor.
        /// </summary>
        public static string sFlipBlock3D_LevelEditor {
            get {
                return ResourceManager.GetString("sFlipBlock3D_LevelEditor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game Level.
        /// </summary>
        public static string sGameLevel {
            get {
                return ResourceManager.GetString("sGameLevel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Help.
        /// </summary>
        public static string sHelp {
            get {
                return ResourceManager.GetString("sHelp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ice Cell 
        ///Number of Steps = 1.
        /// </summary>
        public static string sIceCell1 {
            get {
                return ResourceManager.GetString("sIceCell1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ice Cell
        ///Number of Steps = 2.
        /// </summary>
        public static string sIceCell2 {
            get {
                return ResourceManager.GetString("sIceCell2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ice Cell
        ///Number of Steps = 3.
        /// </summary>
        public static string sIceCell3 {
            get {
                return ResourceManager.GetString("sIceCell3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ice Cell 
        ///Number of Steps = 4.
        /// </summary>
        public static string sIceCell4 {
            get {
                return ResourceManager.GetString("sIceCell4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ice cells.
        /// </summary>
        public static string sIceCells {
            get {
                return ResourceManager.GetString("sIceCells", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Decrement Number of Steps in Ice Cell.
        /// </summary>
        public static string sIceDec1 {
            get {
                return ResourceManager.GetString("sIceDec1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Increment Number of Steps in Ice Cell.
        /// </summary>
        public static string sIceInc1 {
            get {
                return ResourceManager.GetString("sIceInc1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New game level was created!.
        /// </summary>
        public static string sInfoNewLevelConfirmationMessage {
            get {
                return ResourceManager.GetString("sInfoNewLevelConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New level confirmation.
        /// </summary>
        public static string sInfoNewLevelConfirmationTittle {
            get {
                return ResourceManager.GetString("sInfoNewLevelConfirmationTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game level was opened correct!.
        /// </summary>
        public static string sInfoOpenLevelConfirmationMessage {
            get {
                return ResourceManager.GetString("sInfoOpenLevelConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open level confirmation.
        /// </summary>
        public static string sInfoOpenLevelConfirmationTittle {
            get {
                return ResourceManager.GetString("sInfoOpenLevelConfirmationTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game level was saved correct!.
        /// </summary>
        public static string sInfoSaveLevelMessage {
            get {
                return ResourceManager.GetString("sInfoSaveLevelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save level confiramtion.
        /// </summary>
        public static string sInfoSaveLevelTittle {
            get {
                return ResourceManager.GetString("sInfoSaveLevelTittle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Language.
        /// </summary>
        public static string sLanguage {
            get {
                return ResourceManager.GetString("sLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Level dimension control.
        /// </summary>
        public static string sLevelDimensionControl {
            get {
                return ResourceManager.GetString("sLevelDimensionControl", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Level dimension information.
        /// </summary>
        public static string sLevelDimensionInformation {
            get {
                return ResourceManager.GetString("sLevelDimensionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move All Level To
        ///Bottom Left Corner.
        /// </summary>
        public static string sMoveViewBottomLeft {
            get {
                return ResourceManager.GetString("sMoveViewBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move All Level To
        ///Bottom Right Corner.
        /// </summary>
        public static string sMoveViewBottomRight {
            get {
                return ResourceManager.GetString("sMoveViewBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move All Level To
        ///Down Direction.
        /// </summary>
        public static string sMoveViewDown {
            get {
                return ResourceManager.GetString("sMoveViewDown", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move All Level To
        ///Left Direction.
        /// </summary>
        public static string sMoveViewLeft {
            get {
                return ResourceManager.GetString("sMoveViewLeft", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move All Level To
        ///Right Direction.
        /// </summary>
        public static string sMoveViewRight {
            get {
                return ResourceManager.GetString("sMoveViewRight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move All Level To
        ///Top Left Corner.
        /// </summary>
        public static string sMoveViewTopLeft {
            get {
                return ResourceManager.GetString("sMoveViewTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move All Level To
        ///Top Right Corner.
        /// </summary>
        public static string sMoveViewTopRight {
            get {
                return ResourceManager.GetString("sMoveViewTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move All Level To
        ///Up Direction.
        /// </summary>
        public static string sMoveViewUp {
            get {
                return ResourceManager.GetString("sMoveViewUp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Level.
        /// </summary>
        public static string sNewLevel {
            get {
                return ResourceManager.GetString("sNewLevel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Normal Cell 
        ///Number of Steps = 1.
        /// </summary>
        public static string sNormalCell1 {
            get {
                return ResourceManager.GetString("sNormalCell1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Normal Cell
        ///Number of Steps = 2.
        /// </summary>
        public static string sNormalCell2 {
            get {
                return ResourceManager.GetString("sNormalCell2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Normal Cell
        ///Number of Steps = 3.
        /// </summary>
        public static string sNormalCell3 {
            get {
                return ResourceManager.GetString("sNormalCell3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Normal Cell 
        ///Number of Steps = 4.
        /// </summary>
        public static string sNormalCell4 {
            get {
                return ResourceManager.GetString("sNormalCell4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Normal Cells.
        /// </summary>
        public static string sNormalCells {
            get {
                return ResourceManager.GetString("sNormalCells", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Decrement Number of Steps in Normal Cell.
        /// </summary>
        public static string sNormalDec {
            get {
                return ResourceManager.GetString("sNormalDec", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Increment Number of Steps in Normal Cell.
        /// </summary>
        public static string sNormalInc {
            get {
                return ResourceManager.GetString("sNormalInc", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Number of steps.
        /// </summary>
        public static string sNumberOfSteps {
            get {
                return ResourceManager.GetString("sNumberOfSteps", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Number of StepsModyfier.
        /// </summary>
        public static string sNumberOfStepsModyfier {
            get {
                return ResourceManager.GetString("sNumberOfStepsModyfier", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open Level.
        /// </summary>
        public static string sOpenLevel {
            get {
                return ResourceManager.GetString("sOpenLevel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open Manual.
        /// </summary>
        public static string sOpenManual {
            get {
                return ResourceManager.GetString("sOpenManual", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Other Cells.
        /// </summary>
        public static string sOtherCells {
            get {
                return ResourceManager.GetString("sOtherCells", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Position X.
        /// </summary>
        public static string sPositionX {
            get {
                return ResourceManager.GetString("sPositionX", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Position Y.
        /// </summary>
        public static string sPositionY {
            get {
                return ResourceManager.GetString("sPositionY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Level Path.
        /// </summary>
        public static string sProjectPath {
            get {
                return ResourceManager.GetString("sProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Release Date.
        /// </summary>
        public static string sReleaseDate {
            get {
                return ResourceManager.GetString("sReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Resize view to all cells.
        /// </summary>
        public static string sResizeViewToAllCells {
            get {
                return ResourceManager.GetString("sResizeViewToAllCells", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save Level.
        /// </summary>
        public static string sSaveLevel {
            get {
                return ResourceManager.GetString("sSaveLevel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save Level as....
        /// </summary>
        public static string sSaveLevelAs3xDot {
            get {
                return ResourceManager.GetString("sSaveLevelAs3xDot", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Set Defoult View.
        /// </summary>
        public static string sSetDefoultView {
            get {
                return ResourceManager.GetString("sSetDefoultView", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show Bottom Status Bar.
        /// </summary>
        public static string sShowBottomStatusBar {
            get {
                return ResourceManager.GetString("sShowBottomStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show Left Panel.
        /// </summary>
        public static string sShowLeftPanel {
            get {
                return ResourceManager.GetString("sShowLeftPanel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show Right Panel.
        /// </summary>
        public static string sShowRightPanel {
            get {
                return ResourceManager.GetString("sShowRightPanel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show Tool Bar.
        /// </summary>
        public static string sShowToolBar {
            get {
                return ResourceManager.GetString("sShowToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start.
        /// </summary>
        public static string sStart {
            get {
                return ResourceManager.GetString("sStart", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tool Bar Icons Size.
        /// </summary>
        public static string sToolBarIconsSize {
            get {
                return ResourceManager.GetString("sToolBarIconsSize", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Type.
        /// </summary>
        public static string sType {
            get {
                return ResourceManager.GetString("sType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Version Number.
        /// </summary>
        public static string sVersionNumber {
            get {
                return ResourceManager.GetString("sVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu View.
        /// </summary>
        public static string sView {
            get {
                return ResourceManager.GetString("sView", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu View Navigation.
        /// </summary>
        public static string sViewNavigation {
            get {
                return ResourceManager.GetString("sViewNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zoom In Level View.
        /// </summary>
        public static string sZoomInLevelView {
            get {
                return ResourceManager.GetString("sZoomInLevelView", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zoom Out Level View.
        /// </summary>
        public static string sZoomOutLevelView {
            get {
                return ResourceManager.GetString("sZoomOutLevelView", resourceCulture);
            }
        }
    }
}
